name: dev
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      TFVARS: ${{ vars.TFVARS }}
      RESSOURCE_GROUP_MGMT: ${{ vars.RESSOURCE_GROUP_MGMT }}
      STORAGE_ACCOUNT_MGMT: ${{ vars.STORAGE_ACCOUNT_MGMT }}
      LOCATION_MGMT: ${{ vars.LOCATION_MGMT }}
      CONTAINER_TF_NAME: ${{ vars.CONTAINER_TF_NAME }}
      SUBSCRIPTION_NAME: ${{ vars.SUBSCRIPTION_NAME }}
      KEY_TF_CONTAINER: ${{ vars.KEY_TF_CONTAINER }}
      ARM_USE_AZUREAD:  true
      ARM_CLIENT_ID: "24e22525-a0e0-4244-8c6c-faa88c6264f7"
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: "a481f761-3f3d-439f-b737-6e08a56eab93"
      ARM_TENANT_ID: "e6f11c7d-0d9a-4a35-a112-8b8c24f2b5f4"

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Create account storage for tfstate'
        run: |
          chmod +x ${{ vars.SHELL_DIRECTORY }}/create-account-storage.sh
          ${{ vars.SHELL_DIRECTORY }}/create-account-storage.sh
          
      - name: 'Init Terraform'
        run: |
          pwd 
          ls
          chmod +x ${{ vars.SHELL_DIRECTORY }}/init-terraform.sh
          ${{ vars.SHELL_DIRECTORY }}/init-terraform.sh
        working-directory: ${{ vars.TERRAFORM_DIRECTORY }}/env/${{ vars.ENV }}

      - name: 'Plan Terraform'
        run: |
          chmod +x ${{ vars.SHELL_DIRECTORY }}/plan-terraform.sh
          ${{ vars.SHELL_DIRECTORY }}/plan-terraform.sh
        working-directory: ${{ vars.TERRAFORM_DIRECTORY }}/env/${{ vars.ENV }}

      - name: 'Apply Terraform'
        run: |
          chmod +x ${{ vars.SHELL_DIRECTORY }}/apply-terraform.sh
          ${{ vars.SHELL_DIRECTORY }}/apply-terraform.sh
        working-directory: ${{ vars.TERRAFORM_DIRECTORY }}/env/${{ vars.ENV }}

#      - task: PowerShell@2
#        inputs:
#          targetType: 'filePath'
#          pwsh: true
#          filePath: $(PowershellDirectory)/create-account-storage.ps1
#          displayName: 'Create account storage for tfstate'
#      - task: PowerShell@2
#        inputs:
#          targetType: 'filePath'
#          pwsh: true
#          filePath: $(PowershellDirectory)/init-terraform.ps1
#          displayName: 'Init Terraform'
#          workingDirectory: $(TerraformDirectory)/env/$(env)
#      - task: PowerShell@2
#        inputs:
#          targetType: 'filePath'
#          pwsh: true
#          filePath: $(PowershellDirectory)/plan-terraform.ps1
#          displayName: 'Plan Terraform'
#          workingDirectory: $(TerraformDirectory)/env/$(env)
#      - task: PowerShell@2
#        inputs:
#          targetType: 'filePath'
#          pwsh: true
#          filePath: $(PowershellDirectory)/apply-terraform.ps1
#          displayName: 'Apply Terraform'
#          workingDirectory: $(TerraformDirectory)/env/$(env)
